### ISSUE TITLE
date got displayed dirty even if correct on DB

### ISSUE THREAD

**Issue by sdmdev** [brody2consult/cordova-sqlite-storage#253]
I am using wp8.1 silverlight and cordova (target wp8).
Everything works fine in my app but I am experience one weird thing:
After inserting one date for instance 1430323815 (the timestamp of now in sec.), it is saved properly on my DB (I verified it using windows power tool) but when I get its value, I receive something like -516517568. Please is there a way to fix it? If I do a query select a row with date='1430323815' the executing returns an entry but still with some date in this -516517568. Please any hint is appreciated.
If I do that on another new table I cannot reproduce this issue.

**Comment by brody2consult** [comment]
The "`wp8`" version is using the CSharp-SQLite library, which is a somewhat heroic port of sqlite to C# but some stability issues had been reported. If you target Windows Phone 8.1, I highly recommend you consider using the `windows` target which now supports both Windows 8.1 and Windows Phone 8.1.

**Comment by sdmdev** [comment]
thanks brodybits, but what if I dont want to change target? What is your suggestion in this case?

**Comment by brody2consult** [comment]
From your description it sounds like you found a special case where the retrieval of your date goes wrong. If you cannot reproduce this case then I would like to treat this as a minor issue, i.e. non-blocking.

In terms of the `wp8` target, I do want to keep supporting it and fix some known issues since it is needed for PhoneGap build.

If you want to investigate this issue, we have to debug how the csharp-sqlite classes handle the query on your database. Unfortunately, I cannot promise when or even if I will really have time to work on this.

**Comment by jlegido** [comment]
Hi there.

This issue may be another occurrence of https://github.com/litehelpers/Cordova-sqlite-storage/issues/195 ?

**Comment by brody2consult** [comment]
> This issue may be another occurrence of #195 ?

According to the OP:

> If I do that on another new table I cannot reproduce this issue.

**Comment by brody2consult** [comment]
No reproducable scenario. If you find a reproducable scenario, or can even provide a database or database dump that can be used to demonstrate the problem, please report it and I will take another look.
