### ISSUE TITLE
Windows 10 integration

### ISSUE THREAD

**Issue by brody2consult** [brody2consult/cordova-sqlite-storage#272]
This needs to be tested. Not sure if this will work since Windows 10 uses the same package for both Windows desktop and Windows Phone. Pointed out by @vjrantal.

**Comment by vjrantal** [comment]
I have tested that a plugin with a similar build structure (https://github.com/AllJoyn-Cordova/cordova-plugin-alljoyn) can be built as a part of a Windows UWP app, but the Cordova Windows 10 support is currently implemented so that it picks up the referenced desktop project and the end result does not work on phones.

I believe to make these kind of plugins fully supported in the Cordova Windows 10 implementation, something additional would be needed to the feature @TimBarham originally implemented and that allowed multiple targets with project file references.

**Comment by brody2consult** [comment]
Hi @vjrantal it was great to finally speak with you in person at the PhoneGap EU conference in Amsterdam.

Just a reminder that unfortunately, my experience with the Windows platform is still extremely limited and I will still have some very basic questions.

First, can you quickly explain what you mean by a "Windows UWP app"?

My understanding is that at least the Javascript API should be the same for both Windows 10 desktop and Windows Phone 10, or am I already mistaken?

In the case of a library built from C++ (and C), I know that for Windows "Universal" 8.1, the Windows desktop and Windows Phone targets _must_ use different DLL/WINMD builds. From our conversations so far, I suspect this continues to be the case for Windows 10 desktop and Windows Phone 10. Am I correct or am I mistaken somehow?

Assuming that I am correct, one of us should raise an issue on the `cordova-windows` project now that they are ready to release a version with Windows 10 support. I am not sure when I will get a chance to look at this.

**Comment by vjrantal** [comment]
> First, can you quickly explain what you mean by a "Windows UWP app"?

I mean the new types of apps that are only supported on Windows 10 devices https://msdn.microsoft.com/en-us/library/dn894631.aspx. Cordova currently has experimental support for building this types of apps https://github.com/apache/cordova-windows/blob/master/cordova-windows10.md.

One thing to note is that Windows 10 is backwards compatible in a way that the apps you build for Windows 8.1 will run just fine on Windows 10 so one doesn't have to worry about the UWP too much unless there is something specific in that runtime one wants to take advantage of.

> My understanding is that at least the Javascript API should be the same for both Windows 10 desktop and Windows Phone 10, or am I already mistaken?

This is true.

> In the case of a library built from C++ (and C), I know that for Windows "Universal" 8.1, the Windows desktop and Windows Phone targets must use different DLL/WINMD builds. From our conversations so far, I suspect this continues to be the case for Windows 10 desktop and Windows Phone 10. Am I correct or am I mistaken somehow?

This is where things have changed. The "universalness" in Windows 8.1 was achieved by having multiple project files and building different app package for multiple targets. However, in Windows 10, the actual built app package itself is universal in a way that you can run the exact same app on all Windows 10 devices. This is why our current plugin.xml definition is doesn't 100% work with the experimental Cordova Windows 10 support, because we shouldn't need multiple project file references.

> Assuming that I am correct, one of us should raise an issue on the cordova-windows project now that they are ready to release a version with Windows 10 support. I am not sure when I will get a chance to look at this.

That is right. I can take an action on this and will send a pointer once an issue is created.

**Comment by metromg** [comment]
It seems, that the plugin works fine with Windows 10 Apps running on PC or Tablet. 
But with Windows 10 Mobile (Windows Phone 10) it fails to open the specified database. (Tested with Emulator coming with Visual Studio 2015).

When can we expect a fix for this issue?

**Comment by brody2consult** [comment]
I cannot make any promises due to my existing backlog. I recommend that you consider building your app for Windows 8.1 and Windows Phone 8.1, which _should_ also work on Windows 10 and Windows 10 Mobile as well.

**Comment by metromg** [comment]
Yeah, good idea! I've created two packages now, one for Windows 8.1 and one for Windows Phone 8.1, which work on Windows 10 Desktop and Mobile. As soon as this plugin fully supports Windows 10 I'll create an universial package for Windows 10 Devices.

**Comment by brody2consult** [comment]
FYI the Windows 10 integration will be done on the cordova-sqlite-ext version when I get a chance, hopefully in early March. (I am fighting a tight deadline for something else). I would like to record a couple other links before they get lost:
- litehelpers/Cordova-sqlite-storage#254 - _Use offical SQLite packages instead of 2 separate SQLite projects_ by @Gillardo
- litehelpers/cordova-sqlite-ext#9 - _windows VS project corrupt_ - contains info to help someone build with VS 2015, along with some info that may help with the Windows 10 version

_UPDATE_ additional:
- Function Level Linking (/Gy flag) for ARM target may be needed (see https://github.com/litehelpers/cordova-sqlite-ext/commit/fc780f300acef4115de95fe6873887ccb70be58a), ref: http://www.monkey-x.com/Community/posts.php?topic=7739

**Comment by brody2consult** [comment]
FYI the cordova-sqlite-ext version now supports Windows 10. Try it out!

**Comment by Gillardo** [comment]
@brodybits does cordova-sqlite-storage support windows 10 then?

**Comment by brody2consult** [comment]
Not yet. I am planning to include it within the next few weeks. For now please consider using cordova-sqlite-ext.

**Comment by brody2consult** [comment]
Windows 10 is now supported by this plugin version.
