### ISSUE TITLE
Can I specify a [pre-populated db] location in Windows 8.1?

### ISSUE THREAD

**Issue by dcp3450** [brody2consult/cordova-sqlite-storage#276]
I'm working on an app that will have a prepopulated database. Using `myDB = window.sqliteplugin.openDatabase({name:"myDB"});` creates the database at `c\users\[USERNAME]\AppData\Local\Packages\io.cordova.[set of numbers and letter]`

However, when I have the final app I'd like the app to read from my prepopulated database instead of creating its own. I didn't see this option in the documentation. Is there a way to achieve this?

**Comment by brody2consult** [comment]
> creates the database at `c\users\[USERNAME]\AppData\Local\Packages\io.cordova.[set of numbers and letter]`

Looks like you did NOT specify the package ID when you did `cordova create project`.

> However, when I have the final app I'd like the app to read from my prepopulated database instead of creating its own. I didn't see this option in the documentation. Is there a way to achieve this?

You can use the File API plugin to copy the pre-populated database into the right location. I recommend that you _first_ make sure the database is _not_ present in the destination location.

**Comment by dcp3450** [comment]
Thanks for the quick response @brodybits . I used Visual Studio 2015 to create the Cordova project. I didn't see an option to provide the package ID. Where can I locate the FILE API plugin?

**Comment by brody2consult** [comment]
> I used Visual Studio 2015 to create the Cordova project. I didn't see an option to provide the package ID.

Looks like an issue with the Visual Studio Cordova add-on. Should be reported as a bug, perhaps on the Apache Cordova project.

> Where can I locate the FILE API plugin?

https://github.com/apache/cordova-plugin-file

I would like to get this into the Windows "Universal" version at some point. Not too hard for Windows "Universal" since it is mostly Javascript.

**Comment by dcp3450** [comment]
I have it installed. I'm working on the DB now. I've looked over the doc as well. Can you point me to the documentation that reviews your suggestion: getting the current file, determining the correct destination, and copying the file there.

Sorry for the large ask I'm new at working with windows with Cordova.

**Comment by dcp3450** [comment]
I have my database in a local folder at `www/db` and I can get my destination using `Windows.Storage.ApplicationData.current.localFolder.path`. I'm just struggling on how to use the copyTo method. I have the option according to line 1069 of the `FilePrody.js` for Windows located at `/plugins/cordova-plugin-file/src/windows/`. There isn't any documentaiton that specifies how to use the `copyTo` method that I can find.

**Comment by brody2consult** [comment]
What I am thinking is to add the pre-populated database option to the new Windows version as this may help some more users. I can probably work on this next week.

**Comment by dcp3450** [comment]
Yeah, I'm rebuilding an app in Windows that was originally on iPad. When I tried explaining this issue I was told just use a pre-populated database like they did on other apps before I was here. I had to explain that the option isn't there for Windows yet. I did find a solution though:

I used `myDB = window.sqliteplugin.openDatabase({name:"myDB"});` to create and/or my database. Then I used something like this:

```
tx.executeSql("SELECT tbl_name FROM sqlite_master WHERE tbl_name="[table name]"',[],function(tx,res){
    if(res.rows.count > 0){
        //table exists
    } else {
        //table doesn't exist so run some create table and insert commands
    }
});
```

When I run the app the first time it builds out my "pre-loaded" database and does nothing from that point on. I only have 7 tables so it's not too bad but a way to just load a pre-loaded db file or at least provide a sql file that can be parsed would be great in Windows.

**Comment by r4nc1d** [comment]
I had the same issue last night, as a work around I browsed to the database folder
var fileUri = new Uri("www\database.db", UriKind.RelativeOrAbsolute); And then i just copied it to IsolatedStorageFile. That seems to have worked.

**Comment by brody2consult** [comment]
Thanks @r4nc1d. I think it would help others if you are willing to post the code you used to copy and open the database on Windows.

**Comment by brody2consult** [comment]
@dcp3450 I am happy that you have a workaround. Unfortunately I cannot promise when I can add the pre-populated database for Windows due to my current workload.

FYI, I integrated the pre-populated database due to popular demand. I personally would favor the idea of populating the database from a dump file. I also have to add automatic testing of the pre-populated database functionality, when I get a chance.

**Comment by r4nc1d** [comment]
@brodybits, yea sure...I think what i will end up doing is probably Fork your project and see if i can add it in the WP8 section. Any pointers will be helpfull :-) 

``` code
private static void CopyDatabase()
        {
            var fileUri = new Uri("www\\database.db", UriKind.RelativeOrAbsolute);
            SaveFileToIsolatedStorage(fileUri, "database.db");
        }

private static void SaveFileToIsolatedStorage(Uri fileUri, string fileName)
        {
// use a using statement
            var appIsolatedStorage = IsolatedStorageFile.GetUserStoreForApplication();
            var file = appIsolatedStorage.CreateFile(fileName);
            var fileData = Application.GetResourceStream(fileUri);
            var bytes = new byte[4096];

            int count;

            while ((count = fileData.Stream.Read(bytes, 0, 4096)) > 0)
                file.Write(bytes, 0, count);

            file.Close();

        };
```

And then in the MainPage Constructor i just added the CopyDatabase();

``` code
public MainPage()
        {
            InitializeComponent();
            CopyDatabase();
            this.CordovaView.Loaded += CordovaView_Loaded;
        }
```

To make a connection to the DB I use
`var data_base = window.sqlitePlugin.openDatabase({ name: "database.db", createFromLocation: 1 });`

Hope this help, the only problem obviously with this piece of code is that when you rebuild your project you will have to re-add the `CopyDatabase` code.

**Comment by brody2consult** [comment]
@r4nc1d it would be great if you can issue a pull request. But your code needs some rework:
- If the app developer has to modify the MainPage, this feature will not work for developers who are using PhoneGap build. Instead you should add the `CopyDatabase()` call to `SQLitePlugin.open()`
- Also we do not want to copy the database if it is already present, since the application _could_ make its own modifications

A bonus would be to copy the database _only_ if `createFromLocation: 1` was specified. The Javascript detects this option and then adds `createFromResource = "1"` if the option was added exactly as documented. The JSON option handling in this project can be a bit tricky sometimes so I will do this if you have any trouble with it.

Please do not push the changes from your `master` branch. This project has a special branching model so in all likelihood I would use `git cherry-pick` to include your contributions.

Finally, it looks like you are looking at the `wp8` version (which _could_ be built but was never tested on `wp7`). There is also the `windows` version which _also_ targets Windows Phone 8.1 in addition to Windows 8 and 8.1. I am planning to add this to the `windows` version (in Javascript) when I get a chance.

**Comment by r4nc1d** [comment]
Awesome, thanks for the tips. I literally started with phonegap 2 days ago. So still finding my way around it. And yes I agree that the code needs some rework. I basically just wrote that piece of code to see if it will make my project work. I will make the require changes now.

**Comment by brody2consult** [comment]
@r4nc1d that is really good pace! One more thing: it should be possible and more efficient to use `System.IO.File.Copy()` instead of iterating through the stream in C# code. You may want to look at: https://msdn.microsoft.com/en-us/library/vstudio/cc148994%28v=vs.100%29.aspx

I am planning to make a similar improvement to the Android version when I get a chance.

**Comment by r4nc1d** [comment]
This might sound like a weird question, just for testing i used the Forked version that i got from your main branch. I am having difficulty opening the project in Visual Studio. Because obviously i want to change the WP8 section. But I cant open it because there is no sln file. and when i just open the files all the cordova classes are missing so `using WPCordovaClassLib.Cordova` fails. What is the correct way of opening a plugin and making changes. Obv if i want to contribute to the plugin i need to start of correctly.

**Comment by brody2consult** [comment]
What you have to do is create a Cordova project (using the Cordova CLI), add the `wp8` platform, and then add the plugin (also using the Cordova CLI). Your test `wp8` project would be in <your project directory>/platforms/wp8 (if I am not mistaken).

**Comment by ghost** [comment]
So in fact , we can not use [ pre- populated db ] with WP 8.1 ?
I 'm doing a project , everything is fine with Android and iOS, but it does not work with WP .
There is a solution ?

**Comment by r4nc1d** [comment]
@brodybits, thanks i managed to get the project running and made the changes. I am still testing though.

@bastien00, I am working on a solution now. Hopefully ill have something over the weekend.

**Comment by Anthony62039** [comment]
@r4nc1d please give the solution about pre-populated db on wp8.1. when you found something

**Comment by brody2consult** [comment]
I published a version that supports pre-populated database on Windows "Universal" at: https://github.com/brodybits/cordova-sqlite-extras

I will integrate the changes into this project once I get some other issues sorted.

This project will never support pre-populated database on the `wp8` platform (WP8).

**Comment by jjab2020** [comment]
Hello first i would like to thank you for this great work,any example to use this plugins for prepopulated database.
Supported version of this plugins for Windows phone.
Thank your very much

**Comment by brody2consult** [comment]
> any example to use this plugins for prepopulated database.
> Supported version of this plugins for Windows phone.

As documented, you have to use cordova-sqlite-ext to get the pre-populated
database feature. I think there is already a link to a pre-populated
database sample using Ionic.

**Comment by jjab2020** [comment]
thanks, i will try , good time.

**Comment by jjab2020** [comment]
Hello, i have used the cordova-sqlite-ext   plugins in my visual studio 2015 project, below  all the steps :
I have write this code in my js file script to test sqlite prepopulated plugins:
![screenshot1](https://cloud.githubusercontent.com/assets/10273521/18322083/ca03412a-7528-11e6-8db6-3135fbd2d369.png)

i run the visual studio emulator for universal phone in VS 2015 and i have get this errors:
Unhandled exception at line 566, column 9 in ms-appx://io.cordova.myappd1bb49/www/plugins/cordova-sqlite-ext/www/SQLitePlugin.js
0x800a139e - JavaScript runtime error: Database location or iosDatabaseLocation value is now mandatory in openDatabase call.

Please help me to get work this good plugins.

**Comment by brody2consult** [comment]
As documented you also have to specify either `location` or `iosDatabaseLocation` when you open the database.

**Comment by jjab2020** [comment]
Thank you very much my friend it's work like a charm:
The problem that i have missed the  parameter 'location:default' in function call.

var db = window.sqlitePlugin.openDatabase({name: "my.db", location: 'default', createFromLocation: 1});

i have added this parameter and it's work, good job.
Thank you very much again, good plugins good work
👍

**Comment by jjab2020** [comment]
hello,

I have a question about this good plugins.

i want , to pass the result of sqlite select function to another function when the first was finished.
is the option callback work in this plugins.

because the tx.executeSql is asynchron.

how can i wait until the results was returned and executed another function.

Any ideas,any helps.  :)

Thank you very much

**Comment by jjab2020** [comment]
Hello,
I have the same problem as this post:

https://forum.ionicframework.com/t/sqlite-plugin-for-loop-callback/61270

Any ideas , any help.

**Comment by brody2consult** [comment]
@jjab2020 I can think of 2 solutions:
- register a callback on the _last_ executeSql call to find out when it finished
- after the executeSql calls do one more executeSql call with a very simple statement such as `SELECT 1` (or possibly `SELECT NULL`) and wait for the callback

**Comment by jjab2020** [comment]
Thank you i will try this solution but how can I define a callback any example 

Have a good day

**Comment by jjab2020** [comment]
@brodybits, thank you very much for the 2 solutions:

I have try your solution and it's work my friend.

Thank you very much for your good tips.

Have a good day. 👍
