### ISSUE TITLE
Crashes while indexing with PouchDB - needs too much memory

### ISSUE THREAD

**Issue by pablomaurer** [brody2consult/cordova-sqlite-storage#299]
Hi

While syncing from the Database it uses more and more Memory but it still works to sync the whole Database. But then when viewing the data the first time it also hast to index the data and then it crashes after a while.

I already asked a bit related to this on [Stackoverflow](http://stackoverflow.com/questions/31053946/pouchdb-sqlite-indexing-crashes-needs-to-much-memory-on-ios). And i did setup a [SampleApp](https://github.com/mnewmedia/testApp) and also a sampleDatabase which is online for some weeks, maybe longer to reproduce the crash.

I'm not shure if this Plugin is the problem maker, but in the Desktop Browser with with IndexedDB and WebSQL everythign worked fine. Cause of the big size of the Database, I only can use SQLite on IOS..

Best Regards & Thanks a lot!

**Comment by brody2consult** [comment]
Thanks @mnewmedia. I will need 1-2 weeks to look at this since your sample project has to work with multiple dependencies (Ionic and PouchDB).

**Comment by rsutphin** [comment]
I am seeing a similar thing — when PouchDB is building some indexes and using this plugin, there are memory spikes which can result in the OS killing the app. The same data indexes okay using native WebSQL. Like @mnewmedia, I'm trying to use this plugin to get around iOS's WebSQL quotas, but I'm testing compatibility with a dataset that can fit in either.

I'm working on a simplified app which will demonstrate this problem with fewer dependencies. In the meantime:
- @brodybits, a view in PouchDB is materialized as a separate database, so a PouchDB view-using application will have more databases open than other applications using this plugin. Do you think that might be related to this problem?
- @mnewmedia, I took a look at your sample app. Thanks for providing it. One thing I noticed is that you're including the full document in your view (i.e., `emit(doc._id, doc)`). [This is not recommended for PouchDB](http://pouchdb.com/2014/06/17/12-pro-tips-for-better-code-with-pouchdb.html) because you can use the `include_docs` option when querying instead. Not including the full doc will make your index smaller and might give you enough headroom to avoid this problem. You may have other constraints which make including the doc necessary; just thought I should mention it.

**Comment by rsutphin** [comment]
Here's my repro app:

https://github.com/humanpractice/sqlite-cordova-299

Its dependencies are Cordova, PouchDB and Xcode.

**Comment by brody2consult** [comment]
> Its dependencies are Cordova, PouchDB and Xcode.

Normally people use PouchDB with a server. Am I correct that I don't have to run a PouchDB or CouchDB server?

**Comment by rsutphin** [comment]
That's right — this test app loads data directly into the PouchDB instance from a bunch of JS objects. (Our real app syncs from a CouchDB server, but that doesn't seem necessary to trigger this problem.)

**Comment by brody2consult** [comment]
When I run https://github.com/humanpractice/sqlite-cordova-299 on iOS 6.1 it is able to load the records and make all 8 indexes without any problems. When I tried adjusting the project to use 30000 records as described in the readme and using `cordova prepare` to update the iOS project, it also finished loading the records and generating the indexes with no problems on iOS 6.1. I suspect this is a problem with JSON decoding in newer versions of iOS.

I expect to test this further within the next 1-2 weeks but do not promise it. The workaround is to use a series of smaller transactions, as described in this comment: https://github.com/litehelpers/Cordova-sqlite-storage/issues/308#issuecomment-124449072

**Comment by rsutphin** [comment]
@brodybits, my test application doesn't crash on iOS 8 either. Apologies for not making that clear. The crash is hard to simulate in a simple application because the cause seems to be a transient memory spike. A simple application doesn't have a high enough memory floor for the spike to send it over the edge. You can see the memory spike in Xcode's memory utilization viewer, though.

In looking at this yesterday with Instruments, I didn't see any obvious leaks or excess retained memory in cordova-sqlite-storage. The approach I'm going to try next in my app is to lower the memory floor by other means.

Thank you for taking the time to look at it.

FWIW, PouchDB indexing does seem to only load batches of records at a time. You can't control the size of these batches, but they appear to be reasonable (you can see them by enabling PouchDB's debug mode).

**Comment by brody2consult** [comment]
See https://github.com/litehelpers/Cordova-sqlite-storage/issues/308#issuecomment-125416508: I am able to reproduce a crash using this code:

``` Javascript
        var test_rows = 200000;

        var ts_prefix = 'teststring12345';

        var db = window.sqlitePlugin.openDatabase({name: "test.db"});

        var i, j;
        var cq = 'CREATE TABLE IF NOT EXISTS tt (text1 text';
        for (i=2; i<=25; ++i) cq += ', text'+i+ ' text';
        for (i=1; i<=5; ++i) cq += ', int'+i + ' integer';
        for (i=1; i<=5; ++i) cq += ', float'+i + ' float';
        for (i=1; i<=5; ++i) cq += ', nulltext'+i+ ' text DEFAULT NULL';
        cq += ')';

        console.log('cq: ' + cq);

        console.log('test_rows: ' + test_rows);

        db.executeSql('DROP TABLE IF EXISTS tt');

        db.transaction(function(tx) {
            tx.executeSql(cq);
            for (i=1; i<=test_rows; ++i) {
                var vv = [];
                for (j=1; j<=25; ++j) vv.push(ts_prefix + '-' + i + '-' + j);
                for (j=1; j<=5; ++j) vv.push(i*100 + j);
                for (j=1; j<=5; ++j) vv.push(i*101.11 + j*1.101);
                for (j=1; j<=5; ++j) vv.push(null);
                tx.executeSql('INSERT INTO tt VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)', vv);
            }

        }, function(err) {
            console.log('tx error');
        }, function(res) {
            console.log('tx ok');
    });
```

**Comment by rsutphin** [comment]
> FWIW, PouchDB indexing does seem to only load batches of records at a time.

I looked more specifically after reading the repro in #308; PouchDB's indexing transactions contain at most 101 statements. So I don't think that the problem reproduced in #308 is the same as this one.

**Comment by nolanlawson** [comment]
Since PouchDB secondary indexes technically create separate SQLite databases for each index, maybe the issue is that there are too many database open? Have you tested something like:

``` js
for (var i = 0; i < 100; i++) {
  var db = window.sqlitePlugin.openDatabase({name: "test_" + i + ".db"});
  // store a lot of data in the db... 
}
```

And yeah in general I would guess the issue lies somewhere in the SQLite Plugin, especially since this same crash cannot be reproduced in native WebSQL. Does anyone know if the crash is from the WebView or from native Objective-C?

**Comment by rsutphin** [comment]
@nolanlawson, thanks for chiming in.

> Does anyone know if the crash is from the WebView or from native Objective-C?

It doesn't seem to be a crash in the sense of segfault or that sort of internally-caused abnormal termination. It appears to be rapid memory allocation leading to iOS killing the process for using too much memory (and not responding to memory warnings).

It's possible that it's a result of the webview not being aggressive enough in GCing when there's a memory warning — I've found that in the simulator (where the peak memory is higher), the same indexing job can complete. You see that a lot of memory is used, but eventually it goes back down.

But it's also true that even with index building turned off, the same app using this plugin vs. using native WebSQL uses more memory. At the moment I'm trying to work around the problem by deferring other operations until all the indexing has completed.

In the longer term, it seems possible to me that a plugin that implemented more of the WebSQL interface in the native part of the plugin instead of working mostly on the JS side might resolve this — on iOS, the memory used could be freed more deterministically, anyway. But that's a bigger task than my current deadline will allow me to take on.

**Comment by brody2consult** [comment]
Thanks guys for your input and help with testing so far. I have done some preliminary testing where I open 100 database and try adding 1000-5000 records to each database. In general I see the memory increase until the records are added to all of the database and then decrease afterwards. I really will need to do some more testing before drawing any further conclusions.

I am considering the following solutions to help deal with the iOS memory issues:
1. Use a flatter JSON interface between Javascript and the platform code, in a new version available for use under GPL or a commercial license that can be purchased. I already have these enhancements available for Android at https://github.com/litehelpers/Cordova-sqlite-enterprise-free and did some work on similar enhancements for iOS that I expect to publish within the next 1-2 weeks or so.
2. Possible enhancement to implement the existing sql transaction mechanism in smaller chunks, also to be published with a choice of GPL or commercially purchased license.
3. API enhancements to make it easier to run transactions in smaller batches, still to be determined which licensing terms

**Comment by brody2consult** [comment]
Please see the version in https://github.com/litehelpers/Cordova-sqlite-enterprise-free (with a different licensing scheme) for some internal memory improvements. If you continue to see memory issues please file a bug report there.
