### ISSUE TITLE
update

### ISSUE THREAD

**Issue by valix85** [brody2consult/cordova-sqlite-storage#315]
Hi, can i update my db witch app update? if i change db and rebuild it , than i install it on device, db dosen't change. i need able to update my db file and update data in app without remove and reinstall my app...i must deploy an app with  some update.
in device ready i call it:

db = window.sqlitePlugin.openDatabase({
                name: dbname,
                location: 1,
                createFromLocation: 1
            });

thank you very much.

**Comment by brody2consult** [comment]
You can use a different database name and delete the old database file (ignore the error if the old database file name does not exist) in the new app update.

**Comment by mirko77** [comment]
@brodybits I have a question related to this: I need to add a couple of tables to an existing app in production, what are my options? I cannot delete the existing db the user is currently using because that will cause a loss of data.

On top of my head I can easily add a script to create only those 2 tables if the database already exists, just wondering if there is another approach? 

Cheers

**Comment by brody2consult** [comment]
Yes you can simply create the 2 new tables if they do not exist. It is safest to create and populate the new tables _within a single transaction_, so the database would not be left in an intermediate state in case of a failure (the app or OS crashes, for example).

Here is the approach that I would take, pardon the details since I want this to help newcomers as well:

Add a special table to store a database version number in a single row, in a single table, and we assume it is the old version if the table does not exist. Upon startup, first attempt to query the table. If it does not exist, add the new table(s), upgrade existing tables if necessary, and add the database version table with the new database version number _all within a single transaction_.

If the database version table does exist, check the value. For future database versions, if the version number is too low, you would upgrade your database if necessary and then update the version number, again _all within a single transaction_.

Very important: in case you change the database a second time, you cannot assume that the user has already done the first upgrade for a very long time.

Another tip: you can query your version table using db.executeSql() since you only need the result of a single query (the error handler would do the upgrade from the old version, the success handler would either do nothing or upgrade the database in case it has changed again).

**Comment by mirko77** [comment]
Thanks @brodybits, very good info!
