### ISSUE TITLE
REGEXP not working

### ISSUE THREAD

**Issue by Diliz** [brody2consult/cordova-sqlite-storage#361]
Hi,

Actually the REGEXP function is not working, since I saw it is working on ios version, and it was marked as working on android too, I think it's a bug or is it me who didn't understand how it's working, I actually tried to add manually a regexp function, but it's not working, dunno what i've done wrong.

Where I saw it was working (And I tested it for ios, also this post confirm that there's a working regexp function for android too) :

```
https://github.com/litehelpers/Cordova-sqlite-storage/pull/32
```

For more informations, I posted a question on stackoverflow here: 

```
http://stackoverflow.com/questions/33081086/cordova-sqlite-plugin-android-regexp-function
```

If you have another solution or any explanation on how to make regexp to work with your plugin, you will made my day.

Thanks for reading, and maybe for answering!

**Comment by brody2consult** [comment]
I posted an answer to your Stack Overflow question. The information about the Android version in #32 is obsolete since the plugin uses native libraries built in https://github.com/liteglue/Android-sqlite-native-driver.

**Comment by Diliz** [comment]
Ok, I looked at this libraries, as you pointed here I was thinkin it was an obsolete information too, but I needed confirmation about this from someone here! :)

Thanks for answering me, I will take a look at this libraries then, and thanks again.

**Comment by brody2consult** [comment]
Adding the "bug" label since REGEXP was working for Android in the past. Also needs to be added to the `spec` test suite. No promise when I will get a chance to fix this.

**Comment by Diliz** [comment]
No problem, if I got some extra time I will look at it too, and thanks for your answers! :)

I will try some other functions to see if it's the only one affected by this bug or if it's some hidden higher bug.

**Comment by Diliz** [comment]
I saw that you're not using the icu library anymore when compiling the lib.so? (Or is it some other flag who's doing the job, or anything else?) I'm trying to solve this issue, need this regexp function actually, and maybe some more in the icu library later, you're usign amalgamation, which is containing the icu library, but when I add -DSQLITE_ENABLE_ICU to the compile options, there's some errors when trying to find some libraries in the icu headers, maybe you got some idea, I'm still looking at it anyway.

And even while I installed the libicu and all its dependencies it's still making some errors trying to looking at this headers, I tried to change the #include <unicode/someheader.h> by #inclue "unicode/someheader.h", but nothing to do, I'm not able to build with the icu flag.

**Comment by brody2consult** [comment]
In general, I have not been building the lib*.so with ICU. I think it would take a lot of work to add ICU to the build. But I can think of 2 possible solutions.

The sqlcipher variant at https://github.com/litehelpers/Cordova-sqlcipher-adapter is using the https://github.com/sqlcipher/android-database-sqlcipher build which _does_ have the ICU library integrated. If you cannot include the encryption layer you _could_ rebuild android-database-sqlcipher with the normal sqlite3.[hc] instead of the sqlcipher version of sqlite3.[hc].

If you want to attempt the lighter-weight version:

I suspect you already have seen that the Android version depends on two sublayers: https://github.com/liteglue/Android-sqlite-connector, which is a JAR that depends on  https://github.com/liteglue/Android-sqlite-native-driver for the native lib*.so, which can be replaced with another native implementation (such as https://github.com/liteglue/Android-sqlcipher-native-driver).

I made a project at https://github.com/sulite/SQLiteGlue-ICU which builds the native sqlite lib*.so for Android with the ICU library code tightly integrated. SQLite-ICU depends on a version of https://github.com/sqlg/SQLiteGlue-core which was also used to develop Android-sqlite-native-driver (some shared git history). It would take me some work to fix it to work with the Android-sqlite-connector. I may work on this over the next few days but cannot make any promise.

**Comment by Diliz** [comment]
Ok, thanks brody, I will take a look at it, and yep you guessed right, I looked at all this repos you made.

If I get something to work with all of it I'll let you know on this issue thread, thanks for answering again.

EDIT: I tested the cipher version of the plugin this morning, regexp is working on it, and everything I want too, but now I got one more question about it, is there a performance impact while using sqlcipher? Is it always encrypted or can I disable this encryption? And at last, why is this kind of features not available on the main sqlite plugin anymore, seems like there's some defined functions who are not usable now, and they were before... Pretty strange actually! :)

Thanks for answering again, and have a good day.

**Comment by brody2consult** [comment]
@Diliz I just published https://github.com/liteglue/Android-sqlite-native-driver-ICU which you can use to build the native Android lib(s) with ICU (4.4l) embedded. When I build and use the native library with ICU embedded, this plugin passes its full `spec` test suite and the ICU string test is working OK.

Keep in mind that it currently only builds for `armeabi` by default, it should be easy to build for the other CPUs if you know how native NDK build is working. The documentation is very skimpy but _should_ be enough to help you get started.

To build the native library, simply clone the Android-sqlite-native-driver-ICU and **make sure that you do `make init` before `make`** otherwise it will not build.

Please let me know whether or not this works for you.

**Comment by Diliz** [comment]
Thanks again, I will look at it and provide some addons to build for other architectures, no problem.
Again I'll let you know if I run into some problem/issues or if I solve it. See you.

I saw it the minute you posted it x)

EDIT: I found something working with this repo, I saw that there was a problem with the java files, so I tried to modify the one in src/android/io/etc... And I tried to change it by the one here: https://raw.githubusercontent.com/litehelpers/cordova-sqlite-common/cordova-sqlite-common/src/android/io/liteglue/SQLitePlugin.java

Actually I have not looked why it's working and the difference between this old version and the new one, but it's working, and this is the only thing I've changed from the cordova-sqlite-storage plugin, so we got some accurate zone to find from where the bug is coming.

I look at it when I got time, see you.

**Comment by Diliz** [comment]
Hi again, sry I was not able to look deeper in this problem, the use of the old plugin file caused some problems on previous android versions, dunno why, I will take a look at it today, if I find something working with the new plugin and why it was buggy I'll tell you, there was some workaround using the old java file into the new plugin, I "just have to" find what changed from the old java file to the new to see if we can again use the functionnalities who were available in the old version of your plugin. See you, I'll submit the code when I find something to work on.

**Comment by Diliz** [comment]
Hi there, I looked deeper in the plugin, and actually I found why there's some functions missing, there's this condition in the SQLitePlugin.java file:

SQLiteAndroidDatabase mydb = old_impl ? new SQLiteAndroidDatabase() : new SQLiteDatabaseNDK();

I forced to sqliteandroiddatabase type, and actually everything is working on android 5+, tested on android 4.4 and it's not working, dunno why, I will dive more to see what's the problem now, but it's actually on the way to work.

EDIT: The old implementation of the database used some user defined functions I think, but not the ndk one, I don't know how to define user functions with the ndk, it looks pretty hard to do, maybe I'm wrong, if you got some tips to help you add this functions I will do it as fast as I can, have a good day/night, see you.

EDIT2:

This is working on:
nexus 5 2014: armv7l (6.0, api 23)
samsung galaxy tab 4 10.1: armv7l (5.0.2, api21)

Not working on:
samsung galaxy tab 3 10.1: i686 (4.4.2 api 19)
samsung galaxy note 10.1 2014 edition: armv7l (4.4.2 api 19)

Maybe I'm wrong, but the only real difference is in the android version, maybe you know something that is differently used for android versions < Android 5 or something? Any tips is welcome, thanks for reading.

**Comment by brody2consult** [comment]
As I said before, you would have to rebuild the lib*.so libraries using https://github.com/liteglue/Android-sqlite-native-driver (or https://github.com/liteglue/Android-sqlite-native-driver-ICU) and test it in your local project. Please make sure you can do that first otherwise you will potentially have to debug multiple problems at once.

Once you can do this, then you can modify your copy of the https://github.com/liteglue/Android-sqlite-native-driver project. I suggest you look at `native/sqlc.c` and modify the `sqlc_db_open` function with some code to add the "external" sqlite function. You may want to look at `src/ios/SQLitePlugin.m` to see how it is done there.

**Comment by brody2consult** [comment]
REGEXP is now supported in https://github.com/litehelpers/cordova-sqlite-ext.
