### ISSUE TITLE
how to set and get verison for database

### ISSUE THREAD

**Issue by harsh-vardhhan** [brody2consult/cordova-sqlite-storage#389]
Couldn't find any api to set and get database version

**Comment by brody2consult** [comment]
Please see the answer to #312. In short summary: You have to keep track of your own database schema version. Upon startup you should check your db version and if it does not match, upgrade the database and update your version I'd number within a single transaction. This would protect the app in case the upgrade fails due to a temporary error (the device crashes, for example).

I will update the readme very soon.

**Comment by brody2consult** [comment]
There is a better description at: https://github.com/litehelpers/Cordova-sqlite-storage/issues/315#issuecomment-147826027
