### ISSUE TITLE
cordova-ios 4 unstable behavior

### ISSUE THREAD

**Issue by kanoshin** [brody2consult/cordova-sqlite-storage#399]
Hi @brodybits,
I'm experiencing some critical bug after update to cordova-ios@4.0.1 (cordova@5.4.1). I created repository to reproduce it - https://github.com/kanoshin/cordova-bug-reproduction.

It seems that your plugin causes 100% cpu usage and huge memory leak (it looks like eternal loop). Sometimes everything works fine, but sometimes app just hangs after db opens or after transaction opens. Please try to run this app ~20 times and I bet you will reproduce it (both ios simulator and real device have this issue).

App shows current state on the screen ("Done!" means that everything worked fine, any other status  most likely is the problem).

**Comment by brody2consult** [comment]
On Sat, Dec 26, 2015 at 2:57 AM, Kirill Anoshin notifications@github.com
wrote:

> Hi @brodybits https://github.com/brodybits,
> I'm experiencing some critical bug after update to cordova-ios@4.0.1. I
> created repository to reproduce it -
> https://github.com/kanoshin/cordova-bug-reproduction.
> 
> Your demo project uses cordova-plugin-sqlite, which is published from a
> fork in https://github.com/hypery2k/cordova-sqlite-plugin and _NOT_ this
> project. If you continue to use cordova-plugin-sqlite please raise the
> issue there. In general the forks tend to fall out of date.

This project is published as cordova-sqlite-storage.

**Comment by kanoshin** [comment]
I installed 'cordova-sqlite-storage' and the problem is still there (also I made commit to the demo repo).

**Comment by kanoshin** [comment]
Also I figured out that if I wrap open method in SQLitePlugin.m with:

```
[self.commandDelegate runInBackground:^{
    ...
}];
```

then the problem will disappear (or maybe it just reveals less often). I'm unable to reproduce it after this change.

**Comment by brody2consult** [comment]
Thanks! I will probably do this within the next 1-2 of weeks or so (I am on
vacation). Close and delete should probably be done in the background as
well.

**Comment by kanoshin** [comment]
I reported this to the Apache issue tracker - https://issues.apache.org/jira/browse/CB-10276.

**Comment by brody2consult** [comment]
On Tuesday, December 29, 2015, Kirill Anoshin <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> I reported this to the Apache issue tracker -
> https://issues.apache.org/jira/browse/CB-10276.

I read your bug report and have to say that it is not specific enough. Is
your problem with Cordova 4.0 only with this plugin or do you have to
modify any other plugins as well?

I suspect you see the issue with this plugin since it is opens the database
in the main thread then does the transactions in the background thread
pool. If your suggested solution alleviates the problem then I suggest we
simply apply the solution to this plugin, which I can probably do today,
and declare the problem to be solved.

In case you have to modify any other plugins they need to know which ones.

The Cordova maintainers are extremely busy and I think mostly volunteers. I
do not really want to see this extra burden on Cordova unless absolutely
necessary.


## 

Sent from my mobile

**Comment by kanoshin** [comment]
Just found another plugin with this problem and added info about it to the issue.

**Comment by brody2consult** [comment]
On Tuesday, December 29, 2015, Kirill Anoshin notifications@github.com
wrote:

> Just found another plugin [
> https://github.com/katzer/cordova-plugin-printer] with this problem and
> added info about it to the issue.
> 
> Good find!

Can you report the issue on that plugin as well?

Are you able to apply a similar workaround to that plugin? If so, do you
want to raise a pull request with the workaround?

I think it would help others if you can describe the possible workaround in
CB-10276 as well.


## 

Sent from my mobile

**Comment by brody2consult** [comment]
I have modified the iOS version to run _all_ operations (open, close, delete, and execute sql) in the background and am closing this issue. I also raised katzer/cordova-plugin-printer#68 to report this on the cordova-plugin-printer project. Please report if you run into any related problems with this plugin (or in general).
