### ISSUE TITLE
Cordova 6.0.0

### ISSUE THREAD

**Issue by assetsense** [brody2consult/cordova-sqlite-storage#448]
Does this plugin work under Cordova 6.0.0? I am getting plenty of errors:
1. OutOfMemory. The same stuff that used to work under older Cordova, is now causing out of memory errors. I am using Samsung Galaxy Tab A.
2. W/PluginManager(26939): THREAD WARNING: exec() call to SQLitePlugin.backgroundExecuteSqlBatch blocked the main thread for 31ms. Plugin should use CordovaInterface.getThreadPool().
After this error/warning, bulk insert statements are failing.

Are there any major settings such as memory limits or version compatibility that I am missing?

**Comment by assetsense** [comment]
Chris/et all
I hope I did not post an obvious question, my apologies if I did.

Can someone point me to the correct versions and installation steps? I am working on a high priority issue, I greatly appreciate your input.

**Comment by brody2consult** [comment]
I have tested this plugin under Cordova 6.0.0. I really cannot see how upgrading to Cordova 6.0.0 would cause such memory issues.

You can ignore the "THREAD WARNING" since this plugin does execute all SQL in a background thread.

There is a possible memory issue in Android with really large batches which is solved in https://github.com/litehelpers/Cordova-sqlite-enterprise-free (available with GPL and commercial licensing options).
