### ISSUE TITLE
Alter Query Not working

### ISSUE THREAD

**Issue by aqibmapari** [brody2consult/cordova-sqlite-storage#502]
I am also facing this issue.
I have so far tested on android and ios.
It goes into success function but the column is not added.

I have the following code for alter

> function alterTable(tx,tablename,columnname,datatype){
>     tx.executeSql("select "+columnname+" from "+tablename+"",[],function(tx,results){
>                   //console.log("coloumn exists");
>     },
>     function(err){
>           console.log(tablename+" - "+columnname+" select error "+err);
>           tx.executeSql("ALTER TABLE "+tablename+" ADD COLUMN "+columnname+" "+datatype+"",[],function(tx,results){},function(err){console.log(tablename+" - "+columnname+" alter error "+err);})
>      });
> }

The below is the call to this function 

> alterTable(tx,"cformreport","quarter","text");

Please suggest some fix for the same as maintaining app updates is not working due to this issue.

**Comment by aqibmapari** [comment]
@brodybits any thing that can be done to make alter query work.

**Comment by brody2consult** [comment]
This is standard SQLite functionality. Please double-check that you follow the syntax and procedure described at: https://www.sqlite.org/lang_altertable.html

In case you are really stuck please post a test program based on https://github.com/brodybits/Cordova-sqlite-starter-test to demonstrate your problem.

**Comment by brody2consult** [comment]
I added a couple tests to confirm that the ALTER TABLE query is working properly. (It is possible to do ADD COLUMN or RENAME a table.) As I said before this is standard SQLite functionality and is documented in sqlite.org. In case you get stuck somewhere please feel free to ask here or in a new issue **with some sample or reproduction code**.

I did actually find a ~~couple~~ real bug~~s~~ due to this query:
- #517 (minor): did not reject ALTER and a couple other modification operations in a readTransaction, now fixed.
- ~~#530: ALTER TALBLE with RENAME does not seem to work for Windows x86 or x64 builds (not sure when I will get a chance to investigate or fix)~~ _(INVALID)_
