### ISSUE TITLE
Memory Leak when forgetting to close databases?

### ISSUE THREAD

**Issue by massaroni** [brody2consult/cordova-sqlite-storage#520]
Question:  if I dynamically create new databases, maybe dozens or hundreds of them over time, and along the way I let them go out of scope in javascript without ever closing them, would that result in a memory leak on the native side?  Like, would it leave lots of open connections in memory forever?  Or does the native code have some mechanism to periodically clean up resources in memory that haven't been used in a while?

**Comment by brody2consult** [comment]
The connections on the native side would remain open until explicitly closed in JavaScript (or the app terminates). There is no periodic cleanup on the native side. In addition, it is already documented that for Android there is (an intrinsic) limit of 100 connections due to the Android thread pool implementation.

**Comment by massaroni** [comment]
Cool, thanks.  Quick follow up question: if I open two db connections for the same database, in javascript, will they both map to the same connection on the native side, or two different connections?  The reason I ask is that if I close one of them, does it have the side effect of also closing the native connection for the other one as well?

**Comment by brody2consult** [comment]
> if I open two db connections for the same database, in javascript, will they both map to the same connection on the native side

Yes

> if I close one of them, does it have the side effect of also closing the native connection for the other one as well?

Yes (unfortunately). An idea under consideration is to add a database.dispose() method so that the database connection is actually closed once all connections on the JavaScript side have been terminated.

Priority feature development is available through professional support. For more information you may contact: sales@litehelpers.net

**Comment by massaroni** [comment]
Cool, thanks for the quick reply.

> An idea under consideration is to add a database.dispose() method so that the database connection is actually closed once all connections on the JavaScript side have been terminated.

+1
