### ISSUE TITLE
Problems With IOS

### ISSUE THREAD

**Issue by Danius87** [brody2consult/cordova-sqlite-storage#544]
Hello i'm using "Cordova-sqlite-storage" with succesfully in Android with Cordova Cli 5.4.1 e Intel XDK. I would like to run the application on IOS but unfortunately it doesn't work.
So i've created a new project in a MacBook with Intel XDK, and i tried to run the "echoTest" but with no result. The application stops when executes the command  "window.sqlitePlugin.*".
With a blank project with Intel XDK 3522 how can i install and configure correctly the library for working on IOS?
Thanks in advance

**Comment by brody2consult** [comment]
As already documented, this project does not support Intel XDK since it does not seem to honor the `before_plugin_install` hook. Intel XDK as well as PhoneGap CLI, PhoneGap Build, plugman, etc. are supported by the following versions:
- https://github.com/litehelpers/Cordova-sqlite-legacy-build-support
- https://github.com/litehelpers/Cordova-sqlite-evcore-extbuild-free
