### ISSUE TITLE
It is not working in One Plus Two phone

### ISSUE THREAD

**Issue by theanil** [brody2consult/cordova-sqlite-storage#562]
It is not working in One Plus Two phone

document.addEventListener("deviceready", function()
{

```
//alert('in device ready');

db = window.sqlitePlugin.openDatabase({name: "note.db"});
db.transaction(function(tx) {
    tx.executeSql("CREATE TABLE IF NOT EXISTS note (name text primary key, data text)");
}, function(err){
    alert("An error occurred while initializing the app");
});
```

}, false);

 i always get this message "An error occurred while initializing the app"

**Comment by brody2consult** [comment]
Your openDatabase call is missing the location parameter. Please read the documentation, add it and try it again.

In case you continue to have problems:
- Please be sure to try the echoTest and selfTest functions as documented and state the results
- Try waiting for the openDatabase success/error callbacks
- Each error object should have a `code` and `message` member. Please be sure to report the values of both members.

**Comment by theanil** [comment]
document.addEventListener("deviceready", function()
{

```
alert('in device ready');

db = window.sqlitePlugin.openDatabase({name: "note.db", location: 'default'});
db.transaction(function(tx) {
    tx.executeSql("CREATE TABLE IF NOT EXISTS note (name text primary key, data text)");
}, function(err){
    alert("An error occurred while initializing the app: " + err);
});


window.sqlitePlugin.echoTest(function() {
    console.log('ECHO test OK');
    alert('ECHO test OK');
  });

window.sqlitePlugin.selfTest(function() {
    console.log('SELF test OK');
    alert('SELF test OK');
  });
```

}, false);

i am not getting message for echo test also

**Comment by theanil** [comment]
Getting this message

An error occurred while initializing the app:
Error: invalid database handle

**Comment by brody2consult** [comment]
Since you report that the echoTest does not work I suspect there is an issue with your installation. Can you please check the following:

Try making a very simple app with a plugin such as cordova-plugin-dialogs or perhaps some variation of cordova-plugin-echo and get it working.

Then within a git clone of https://github.com/brodybits/Cordova-sqlite-bootstrap-test:
- do `cordova plugin add cordova-sqlite-storage`
- do `cordova platform add android`
- try running it on your device

If Cordova-sqlite-bootstrap-test works for you, you may want to use it as a starting point since it is has CC0 (public domain) license.

In your own project, I suggest you try echoTest and selfTest one at a time _without_ the database access code.

**Comment by theanil** [comment]
Thanks it is working, problem was with my code i was using older version of your plugin, now changed to latest version and it started working.

Thanks for your fast support.

**Comment by brody2consult** [comment]
Thanks for the confirmation.

**Comment by theanil** [comment]
Now when i try to build on iOS i am getting this message

Error - The following 3rd-party plugin is causing the build to fail and may need to be updated to a newer version: io.litehelpers.cordova.sqlite

```
<plugin name="io.litehelpers.cordova.sqlite" source="pgb" />
```

i am using following configuration

**Comment by brody2consult** [comment]
That is an old ID. The new ID is: cordova-sqlite-storage

It will not work with tools such as PhoneGap CLI, PhoneGap Build, Plugman, Intel XDK, etc. since they do not honor the `before_plugin_install` hook. For these tools you can use:
- https://github.com/litehelpers/Cordova-sqlite-legacy-build-support
- https://github.com/litehelpers/Cordova-sqlite-evcore-extbuild-free (available under GPL or commercial license options)

**Comment by theanil** [comment]
I have compiled for iOS app on phone gap build upto 3.9.2

but it is not compiling in these version

4.2.0  
4.1.1
4.1.0
4.0.1

please changes in the plugin so it will be compatible with latest version of phongap build

**Comment by theanil** [comment]
Now as i have used this

```
<gap:plugin name="cordova-sqlite-evcore-extbuild-free" source="npm" />
```

and it is compiled properly
