### ISSUE TITLE
IOS 10 support

### ISSUE THREAD

**Issue by boypower187** [brody2consult/cordova-sqlite-storage#567]
I love using this plugin as it is great but it does not work on my app on IOS 10 when i upgraded the iPhone. Do you have any plans for updating it? It return me a db null error when i open a sqlite file and the self test function will not work. My app was fine with ios 9 and lower.

**Comment by brody2consult** [comment]
I will investigate this over the next few weeks or so. May be related to #568 _and_ litehelpers/Cordova-sqlcipher-adapter#22 (iOS WKWebView support).

**Comment by brody2consult** [comment]
With Xcode 8.1 beta it works for me if I do `cordova prepare` before attempting to run on iOS 10.1 (simulator). Please confirm if this helps or not.

**Comment by boypower187** [comment]
Ok thanks brodybits i got it to work.

**Comment by brux88** [comment]
I upgraded to ios 10 and does not work sqlite, a solution has been found?

**Comment by brody2consult** [comment]
> I upgraded to ios 10 and does not work sqlite, a solution has been found?

@brux88 did you do `cordova prepare`?

**Comment by brux88** [comment]
if i did cordova prepare ios work,I do not understand why it worked before with ios 9.3. you can not update the plugin so that it works without doing every time cordova prepare?

**Comment by brody2consult** [comment]
@brux88 I added the **bug** label to get this fixed so you don't have to do `cordova prepare` every time. I think this is an issue with the Cordova framework but still have to do some further testing to be sure. From initial testing this also seems to be an issue with simple plugins such as cordova-plugin-dialogs.

I would like to ask for some patience with this one. I am already 100% busy between the free software and work for a paid client, and the Cordova framework is mostly maintained by some very busy volunteers.

My personal observations is that this issue came up after I upgraded from Xcode 7 to Xcode 8 on both my test devices (iOS 8 and iOS 10). I cannot promise when I can give you a better explanation.

**Comment by brody2consult** [comment]
This is now reported in: https://issues.apache.org/jira/browse/CB-12046

**Comment by brux88** [comment]
hello, doing cordova prepare works on ios 10 but on previous verisoni not, it happens?

**Comment by brody2consult** [comment]
The issue reported here and in CB-12046 is not a problem in cordova-ios@4.3.0 (included by cordova-cli@6.4.0), closing.
