### ISSUE TITLE
Fetching plugin "cordova-sqlite-storage@1.0.6" via npm Failed to fetch plugin cordova-sqlite-storage

### ISSUE THREAD

**Issue by roblesjohnryan** [brody2consult/cordova-sqlite-storage#588]
Hi Brody, 
Good day!

Im trying to build my application using build phonegap cli-6.3.0 which inlcudes 

<plugin name="cordova-sqlite-storage" spec="1.0.6" source="npm"/>

But i got this error: 

Error - Plugin (or a specific plugin version) not found in external repo: cordova-sqlite-storage@1.0.6": Fetching plugin "cordova-sqlite-storage@1.0.6" via npm Failed to fetch plugin cordova-sqlite-storage

Is there anything that i need to do to fix this thanks! It's working before in cli5.20

**Comment by brody2consult** [comment]
As already documented PhoneGap CLI is not supported since it does not honor the before_plugin_install hook. The following versions are supported with PhoneGap CLI, PhoneGap Build, Intel XDK, etc:
- https://github.com/litehelpers/Cordova-sqlite-legacy-build-support (permissive license)
- https://github.com/litehelpers/Cordova-sqlite-evcore-extbuild-free (GPL or commercial license options)

**Comment by roblesjohnryan** [comment]
Thanks @brodybits . I added this code plugin name="cordova-sqlite-evcore-extbuild-free" source="npm" spec="0.8.0"  as well as   plugin name="cordova-sqlite-storage" source="npm" spec="~1.2.1" in my config.xml file but still no luck to make it working. The application was successfully build in Build.Phonegap.com but the app cant load data retrieve from server to sqlite. My device is Ipad iOS 10.
