### ISSUE TITLE
About ""no Such table" errors (and table exists)

### ISSUE THREAD

**Issue by cerge** [brody2consult/cordova-sqlite-storage#634]
Hello, please, if some expert can help me, my problem is: -Im working with Ionic + sqlite prepopulated database and it worked fine after a lot of work. Now, I've updated the file (all seems ok, I've checked integrity, etc. so it seems the file and database schema seems ok) but when I want to open it, I have different errors, basically, with the style "no Such table: mytable ".
I used different ways to open it, by sample, location:'default', 1 and 2 , androidDatabaseImplementation: 2,  androidLockWorkaround: 1 ,etc but nothing is solved. Also, Iwas reading a lot of sites , I've seen some issues of this style but I cant see many solutions and really I need some urgent help. 
Here http://stackoverflow.com/questions/28922548/open-prepopulated-sqlite-dtabase-in-cordova-for-android-and-visual-studio, I see some comments like "but it does not copy the prepopulated database It always creates an empty one. " (And seems the user fixed it using a previous version, now deprecated and updated) and really I was asking myself if on my case it exactly happens this, I mean, it copy the file (in fact, with Gapdebug and console, I see the Sequence "device ready", "OPEN database: mydb.db - OK", "DB opened: mydb.db") but after this steps, always some "no such table" error.
Thanks in advance for some help or idea.

**Comment by brody2consult** [comment]
Closing as invalid since this question should have been raised in cordova-sqlite-ext or Cordova-sqlite-help.

As I already documented in cordova-sqlite-ext:
> - The pre-populated database file is ignored if the database file with the same name already exists in your database file location.

During development it is recommended to uninstall the app if the pre-populated database is updated.

In case you need to update the pre-populated database for an app with existing users (https://github.com/litehelpers/cordova-sqlite-ext/issues/55#issuecomment-279468253):
> Assuming the app did not store any user data in the database:
> 
> The new version of your app should use a new database with a new name. It should also be smart enough to delete the old database if it exists (or just call sqlitePlugin.deleteDatabase and ignore the success/error callbacks).
> 
> Please keep in mind that it is extreemely difficult if not impossible to know how long it will take for users to upgrade their apps. So newer versions of the app should just include the logic to cleanup the old database if it exists.

**Comment by jeevithaBA** [comment]
@brodybits 
Hi,
I m stuck with same issue as mentioned above, since from week,anyone please help me
I’m working on an ionic1 app…
I’m currently having trouble with the iOS version.
and iam using cordova sqlite plugin,and here db is getting opened but cordovasqlite.execute function(), not working instead iam getting error code:5,message:"no such table:table-name"
for opening database iam using,

if(ionic.Platform.isIOS())
{
console.log(‘database is iso’);
var db = $cordovaSQLite.openDB({name: ‘olarcniapp.db’, iosDatabaseLocation: ‘Library’}); //ios device

	}
	else
	{
			console.log('database is android');
		var	db = $cordovaSQLite.openDB({name:'olarcniapp.db',location:'default'});  // android device

	}

<img width="2048" alt="screen shot 2018-12-26 at 6 47 17 pm" src="https://user-images.githubusercontent.com/19791835/50515161-12b3fa80-0ac9-11e9-9f66-3df645915e51.png">

**Comment by jeevithaBA** [comment]
@brodybits 
Hi,
I m stuck with same issue as mentioned above, since from week,anyone please help me
I’m working on an ionic1 app…
I’m currently having trouble with the iOS version.
and iam using cordova sqlite plugin,and here db is getting opened but cordovasqlite.execute function(), not working instead iam getting error **code:5,message:"no such table:table-name"**
for opening database iam using,

if(ionic.Platform.isIOS())
{
console.log(‘database is iso’);
var db = $cordovaSQLite.openDB({name: ‘olarcniapp.db’, iosDatabaseLocation: ‘Library’}); //ios device

}
else
{
		console.log('database is android');
	var	db = $cordovaSQLite.openDB({name:'olarcniapp.db',location:'default'});  // android device

}



<img width="2048" alt="screen shot 2018-12-26 at 6 47 17 pm" src="https://user-images.githubusercontent.com/19791835/50515209-56a6ff80-0ac9-11e9-9392-3f80e1ad6757.png">

**Comment by brody2consult** [comment]
> I m stuck with same issue as mentioned above
> [...]

Same question as <https://github.com/litehelpers/Cordova-sqlite-storage/issues/482#issuecomment-450127384>, same answer:

It looks to me like your database was opened but your table was never created.

Please raise that kind of question in <https://github.com/litehelpers/Cordova-sqlite-help/issues>, not in a closed issue.

And please do not raise the same question in multiple places.
