### ISSUE TITLE
Unable to insert new records;bcoz of space constraint 

### ISSUE THREAD

**Issue by prasadyallapu** [brody2consult/cordova-sqlite-storage#693]
I am working on hybrid mobile app(ionic).Currently, we are facing a problem with inserting new data(ios) into a table due to space limit.

Is there a way to increase the size? or
Is there any way to compress the database?

Need inputs from you folks

Regards
Prasad

**Comment by brody2consult** [comment]
My apologies for the delay, need more information to investigate. Please double-check that you are using sqlitePlugin.openDatabase. You should never encounter arbitrary database size limit if you use this plugin.

**WARNING:** If you use window.openDatabase instead of sqlitePlugin.openDatabase you will run into possible database size limit.
