### ISSUE TITLE
How to connect to other native application database 

### ISSUE THREAD

**Issue by yasser-mas** [brody2consult/cordova-sqlite-storage#747]
I have native application which has shared database, I want to connect to this database by ionic native sqlite.

**Comment by brody2consult** [comment]
I do not understand what you mean by "shared database".

In case of a ContentProvider on Android you have to use <https://github.com/phearme/cordova-ContentProviderPlugin> as I said in #746.

In case of other code that uses the same database within the same Android APK you have use the `androidDatabaseImplementation: 2` setting in order to avoid database corruption risk due to "multiple SQLite problem" on Android as described in <http://ericsink.com/entries/multiple_sqlite_problem.html> (see #626).

**Comment by brody2consult** [comment]
Closing due to lack of response
