### ISSUE TITLE
Difference between Batch and Transaction

### ISSUE THREAD

**Issue by GuilhermeLessa** [brody2consult/cordova-sqlite-storage#793]
this is valid and right for the cordovoa-sqlite-storage?
https://stackoverflow.com/questions/31680259/what-is-the-difference-between-sql-batch-and-transaction-in-orientdb

sqlBatch() dont respect order or guarantee success of all commands?

When should I use batch or transaction?

**Comment by brody2consult** [comment]
> https://stackoverflow.com/questions/31680259/what-is-the-difference-between-sql-batch-and-transaction-in-orientdb

This plugin also uses transactions for sqlBatch() operations. The plugin will automatically execute the `BEGIN` statement before executing the statements requested in sqlBatch() call. In case any of the statements in sqlBatch() call results in an error the plugin JavaScript will automatically do a `ROLLBACK`. If there are no errors in the batch, the plugin will execute `COMMIT` at the end of the batch. This is already documented in <https://github.com/litehelpers/Cordova-sqlite-storage#sql-batch-transactions> (could use some a more detailed explanation though).

I think this is different from the behavior of Orient DB, according to the StackOverflow link.

> sqlBatch() dont respect order

sqlBatch() will execute the statements in the order given, guaranteed

>  or guarantee success of all commands?

sqlBatch() attempts to execute all statements requested (assuming they are not blocked by other requests in the internal queue), triggers success callback if all statements succeed, otherwise triggers error callback

> When should I use batch or transaction?

I cannot make the decision for you. There are some tradeoffs involved, up to you to determine which one works best for the needs of your application.

Marked as a `doc-todo` issue, hope I will have a chance to improve the documentation regarding batch and transaction calls.

In general I would prefer to answer this kind of question at: <https://github.com/litehelpers/Cordova-sqlite-help/issues>
