### ISSUE TITLE
No such table found error when trying to get data from downloaded sqlite db file in ios

### ISSUE THREAD

**Issue by shaik-azmat** [brody2consult/cordova-sqlite-storage#890]
HI,
I have downloaded sqlite db file to location :cordova.file.dataDirectory+"Library/LocalDatabase" from my server, unzipped that file to same location. After that when i try to open db using

window.sqlitePlugin.openDatabase({
name :'MBZ2X8.db.zip',
key: '',
location: 2
},function (success) {
},function(err){
});

opening db is success but I am getting no such table found error while trying to access any table . same is working in android like a charm

**Comment by AubreyHewes** [comment]
This happens on iOS? (I assume this as you do not give enough information)

 ...You are opening a database that does not (yet) exist and is therefore created and as such has no tables..

This is due to the `location` parameter and also why it works on Android. See the [README.md](https://github.com/xpbrew/cordova-sqlite-storage#opening-a-database). Hope this helps!

**Comment by brody2consult** [comment]
That does not look right. I recommend that you use the cordova-plugin-file and any other utilities needed to install an unzipped database file into the right location.
