### ISSUE TITLE
Browser Support ?

### ISSUE THREAD

**Issue by Pratz007-tech** [brody2consult/cordova-sqlite-storage#951]
Does this plugin has been updated for browser support ? Please let me know. I am stuck into a major issue as this plugin is not working on web (chrome browser). I got error saying : openDatabase of undefined , where function used is window.sqlitePlugin.openDatabase. Any help would really be appreciated. Thanks in advance.

**Comment by Chris2011** [comment]
I'm using NanoSQL and I'm searching for an alternative. I found this plugin and I'm also interested whether there will be a fallback to WebSQL or IndexedDB, when I try my App in the browser or not. That would be good.

**Comment by craig-at-rsg** [comment]
Not all browsers use SQLite, but if it's just for development (like with "ionic serve"), you can do something like this:

```
    createDb(params) {
        if (CONSTANTS.IS_DEVICE) {
            return this.sqlite.create(params)
        } else {
            return Promise.resolve(win.openDatabase(params.name, '1.0', 'database', 5 * 1024 * 1024));
        }
    }
```

That IS_DEVICE setting is mine, set depending on the platform. The resulting db object works a little differently than this plugin's object - I'm calling db.transaction (which works a little differently) instead of db.executeSql for the browser code.

**Comment by brody2consult** [comment]
The browser platform is now supported.
